version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8765:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: docker/php
    ports:
      - ":9000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    ports:
      - "3309:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./logs/mysql:/var/log
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
      - MYSQL_DATABASE=bugtracker
    networks:
      - app-network

networks:
  app-network:
